In [16]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv("D:/PSG/PSG-Z/SEM 5/20XW58 MACHINE LEARNING LAB/ws9-SVC/datasets/tumor1.csv")

In [18]:
del df['Sample code number']

In [19]:
# df = df[0:1000]

In [20]:
df_arr = df[df.columns[:-1]].to_numpy()

In [21]:
df_arr

array([[ 5,  1,  1, ...,  3,  1,  1],
       [ 5,  4,  4, ...,  3,  2,  1],
       [ 3,  1,  1, ...,  3,  1,  1],
       ...,
       [ 5, 10, 10, ...,  8, 10,  2],
       [ 4,  8,  6, ..., 10,  6,  1],
       [ 4,  8,  8, ..., 10,  4,  1]], dtype=int64)

In [22]:
A = []

for i in range(len(df_arr)):
    rowe = []
    for j in range(len(df_arr)):
        dist = 0
        if(i==j):
            rowe.append(dist)
        else:
            for k in range(len(df_arr[i])):
                dist += (df_arr[i][k] - df_arr[j][k])**2
            rowe.append(dist**0.5)
    A.append(rowe)

In [23]:
A = np.array(A)

In [24]:
A

array([[ 0.        , 11.87434209,  2.23606798, ..., 17.3781472 ,
        12.9614814 , 13.89244399],
       [11.87434209,  0.        , 11.3137085 , ..., 14.6628783 ,
        11.78982612, 10.95445115],
       [ 2.23606798, 11.3137085 ,  0.        , ..., 17.40689519,
        12.76714533, 13.6381817 ],
       ...,
       [17.3781472 , 14.6628783 , 17.40689519, ...,  0.        ,
         7.74596669,  8.18535277],
       [12.9614814 , 11.78982612, 12.76714533, ...,  7.74596669,
         0.        ,  3.31662479],
       [13.89244399, 10.95445115, 13.6381817 , ...,  8.18535277,
         3.31662479,  0.        ]])

In [25]:
D = []

for i in range(len(df_arr)):
    rowe = []
    for j in range(len(df_arr)):
        deg = 0
        if(i==j):
            deg = len(A[0])-1
            rowe.append(deg)
        else:
            rowe.append(deg)
    D.append(rowe)

In [26]:
D = np.array(D)

In [27]:
D

array([[2048,    0,    0, ...,    0,    0,    0],
       [   0, 2048,    0, ...,    0,    0,    0],
       [   0,    0, 2048, ...,    0,    0,    0],
       ...,
       [   0,    0,    0, ..., 2048,    0,    0],
       [   0,    0,    0, ...,    0, 2048,    0],
       [   0,    0,    0, ...,    0,    0, 2048]])

In [28]:
L = D-A

In [31]:
val,vec = np.linalg.eig(L)

In [34]:
print(val)

[-20064.19698481+0.j  12150.66020691+0.j   3306.53629967+0.j ...
   2048.        +0.j   2048.        +0.j   2048.        +0.j]
