In [31]:
import pandas as pd
from sklearn import datasets
import numpy as np

In [32]:
iris = datasets.load_iris()
data = iris.data

In [33]:
def pca(X,k=2):
    df = X.copy()
    
    df = df-df.mean()
    
    covar = list(df.cov().values)
    
    val,vec = np.linalg.eig(covar)
    
    idx = val.argsort()[::-1]
    
    val = val[idx]
    vec = vec[:,idx]
    print(vec)
    for i in range(k):
        vec[i] = vec[i]/np.linalg.norm(vec[i])
    W = vec[:k]
    print(W,np.linalg.norm(W[:1]))
    Z = X.dot(W.T)
    Z.columns = ["P"+str(i) for i in range(1,k+1)]
    return Z

In [34]:
pca(pd.DataFrame(data),2)

[[ 0.36138659 -0.65658877 -0.58202985  0.31548719]
 [-0.08452251 -0.73016143  0.59791083 -0.3197231 ]
 [ 0.85667061  0.17337266  0.07623608 -0.47983899]
 [ 0.3582892   0.07548102  0.54583143  0.75365743]]
[[ 0.36138659 -0.65658877 -0.58202985  0.31548719]
 [-0.08452251 -0.73016143  0.59791083 -0.3197231 ]] 1.0


P1        P2
0   -1.206733 -2.213499
1   -0.950716 -1.831514
2   -1.096108 -2.020433
3   -1.182994 -1.819382
4   -1.308531 -2.278063
..        ...       ...
145 -1.849411 -0.383012
146 -1.675460  0.024185
147 -2.016334 -0.270191
148 -2.409146 -0.513233
149 -2.238061 -0.215323

[150 rows x 2 columns]